# Site settings
title: "Mariana Campos"
email: marianaalbuquerque02@gmail.com
description: "Mari Campos's Personal Site"
baseurl: ""
url: "http://maricampos.github.io"
title_description: "Hi, I am Mariana! I am a Software Developer at Tempest Security Intelligence. I work with Golang and Javascript. Also, I'm a Master's student in the field of Artificial Inteligence at the University of Pernambuco. I'm live in Recife, BR."
title_image: "http://i.imgur.com/VSI9h3S.jpg"
google_analytics: "UA-162503750-1"
disqus_account: 
github_repository: https://maricampos.github.io
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: maricamppos
github_username:  mariCampos
linkedin_link: http://www.linkedin.com/in/maricamppos
google_plus_link: 
stackoverflow_link:

# Footer
footer_left: "Template made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
